/**
 * api/auth.ts — 登录验活 + 环境绑定。
 *
 * 登录流程：
 *   ① GET /meta/instances 选实例
 *   ② 用户输入自持的 user_key（sk-mem-…）
 *   ③ POST /meta/auth/verify（Header 仅 X-Tdai-Service-Id，body 带 user_key）
 *   ④ data.valid === true → 登录成功，前端把 { instance_id, user_key, user } 写入 session
 * 无 OAuth、无 Cookie；见 lib/panelSession.ts。
 */
import { request, metaCall } from './base';
import type { PublicUser } from './types';

export const authVerifyApi = {
  /** 登录验活：Header 仅带实例 ID，user_key 只放 body（meta-api.openapi.yaml §auth/verify） */
  verify: (instanceId: string, userKey: string) =>
    metaCall<{ valid: boolean; user?: PublicUser }>(
      'auth/verify',
      { user_key: userKey },
      { 'X-Tdai-Service-Id': instanceId }
    ),
};

export interface AuthMethod {
  id: string;
  type: 'user_key' | 'woa';
  display_name: string;
  enabled: boolean;
}

/**
 * user_key 登录（兼容用户自持 key）。
 *
 * 与 WOA 流程的两步确认同构：先 preview 看清"这把 key 属于谁"，再 login 确认。
 * 系统内没有这把 key 时，login 会用它新建账号（首次登录即注册）。
 *
 * 走 Panel 而非前端直连 core：建号需要实例 admin 凭据，前端拿不到。
 */
export const userKeyLoginApi = {
  preview: (instanceId: string, userKey: string) =>
    request<{
      exists: boolean;
      user_id?: string;
      username?: string;
      display_name?: string;
      user_type?: string;
    }>('POST', '/api/v1/auth/user-key/preview', {
      instance_id: instanceId,
      user_key: userKey,
    }),
  login: (instanceId: string, userKey: string, username?: string) =>
    request<{
      authenticated: boolean;
      instance_id: string;
      user_id: string;
      user?: PublicUser;
      created: boolean;
    }>('POST', '/api/v1/auth/user-key/login', {
      instance_id: instanceId,
      user_key: userKey,
      username,
    }),
};

export const authMethodsApi = {
  list: () => request<{ methods: AuthMethod[] }>('GET', '/api/v1/auth/methods'),
  loginWoa: (instanceId: string, returnTo = '/') => {
    const params = new URLSearchParams({ instance_id: instanceId, return_to: returnTo });
    window.location.assign(`/api/v1/auth/idp/woa/login?${params.toString()}`);
  },
  session: (instanceId?: string) => {
    const query = instanceId ? `?instance_id=${encodeURIComponent(instanceId)}` : '';
    return request<{
      authenticated: boolean;
      method?: 'idp';
      instance_id?: string;
      user_id?: string;
      provider_id?: string;
      display_name?: string;
      user?: PublicUser;
      expires_at?: number;
      pending?: boolean;
      pending_identity?: {
        display_name?: string;
        login_name?: string;
        subject?: string;
      };
    }>('GET', `/api/v1/auth/session${query}`);
  },
  /**
   * 预览用户填的 user_key 在系统内是否已有对应账号。
   * exists=true 时返回该账号信息，供用户确认"绑定到它"还是"新建"。
   */
  previewWoaKey: (userKey: string) =>
    request<{
      exists: boolean;
      user_id?: string;
      username?: string;
      display_name?: string;
      user_type?: string;
    }>('POST', '/api/v1/auth/idp/woa/preview-key', { user_key: userKey }),
  completeWoa: (input: {
    username?: string;
    userKey?: string;
    customUserKey?: string;
  }) =>
    request<{
      authenticated: boolean;
      instance_id: string;
      user_id: string;
      user?: PublicUser;
      user_key?: string;
      user_key_autogenerated?: boolean;
    }>(
      'POST',
      '/api/v1/auth/idp/woa/complete',
      {
        username: input.username,
        // 两个字段都必须传：后端 completePendingWoaLogin 取
        // `input.userKey || input.customUserKey`。此前只发了 custom_user_key，
        // 而调用方（LoginGate）传的是 userKey → 后端收到空 key →
        // 400 INVALID_USER_KEY，建号请求根本发不出去。
        user_key: input.userKey,
        custom_user_key: input.customUserKey,
      },
    ),
  /**
   * 放弃 WOA 待确认登录，改用 user_key 登录。
   *
   * 后端会清掉 pending Cookie 并下发一个抑制标记：网关对每次请求都会注入 WOA 身份头，
   * 只清 pending 的话刷新页面会被立刻重新弹回 WOA 确认页。
   */
  dismissWoa: () => request<{ ok: boolean }>('POST', '/api/v1/auth/idp/woa/dismiss'),

  /**
   * 撤销 dismiss，改回 iOA 登录（清除抑制标记）。
   *
   * 与 dismissWoa 成对：用户在 user_key 页点「切换到 iOA 登录」时调用，
   * 否则之前落下的抑制标记会让 WOA ingress 直接放行、停在 user_key 表单。
   */
  resumeWoa: () => request<{ ok: boolean }>('POST', '/api/v1/auth/idp/woa/resume'),
};

// ========================= Environment Bindings =========================
//
// ⚠️ 当前部署未注册 /api/v1/users/* 路由，以下接口可能 404。
// 保留代码用于兼容仍启用该路由的环境；若某个页面依赖这组接口，请先确认路由已注册。

/**
 * 环境绑定（environment_bindings）：把用户在外部环境（IDE / 编程助手等）的
 * 外部 user_id 与本平台 user 关联，供 proxy 通过 (environment, environment_user_id)
 * 反查到团队 / agent / task。
 *
 * 唯一约束：(environment, environment_user_id) 全局唯一；被他人占用 → 409。
 */
export interface EnvironmentBinding {
  id: string;
  user_id: string;
  environment: string;
  environment_user_id: string;
  created_at: string;
  updated_at: string;
}

export const environmentBindingsApi = {
  /** 列出当前登录用户的全部绑定 */
  list: () => request<EnvironmentBinding[]>('GET', '/api/v1/users/me/environment-bindings'),

  /** 新增一条绑定（幂等：同 user 重复 POST 同样的 (env, env_user_id) 不报错） */
  create: (data: { environment: string; environment_user_id: string }) =>
    request<EnvironmentBinding>('POST', '/api/v1/users/me/environment-bindings', data),

  /** 删除一条绑定（只能删自己的；删别人 → 403） */
  remove: (id: string) => request<{ ok: boolean }>('DELETE', `/api/v1/users/me/environment-bindings/${id}`),
};
