import { randomUUID } from 'node:crypto';
import type { Logger } from '../infra/logger.js';
import type { PanelAuthConfig } from '../config/panel-config.js';
import { InstanceRegistry } from '../config/instance-registry.js';
import type { MetaKernelPort } from '../kernel/ports/meta-kernel-port.js';
import type { MetaCallContext } from '../kernel/types.js';
import { FileIdentityStore, decryptSecret, encryptSecret } from './identity-store.js';
import { MemorySessionStore, type IdpSession, type SessionUser } from './session-store.js';
import { AuthProviderRegistry } from './provider-registry.js';
import { WoaProvider } from './woa-provider.js';
import type { ExternalIdentity, HeaderInjectedProvider } from './types.js';

export class PanelAuthError extends Error {
  constructor(readonly code: string, message: string, readonly status = 401) {
    super(message);
    this.name = 'PanelAuthError';
  }
}

export interface AuthMethodView {
  id: string;
  type: 'user_key' | 'woa';
  display_name: string;
  enabled: boolean;
}

export interface IdpLoginResult {
  session: IdpSession;
  identity: ExternalIdentity;
  /** 一次性展示的新建账号 user_key（供用户复制到客户端连 proxy）；已绑定用户复用登录时为空。 */
  userKeyDisplay?: string;
  /** true=该 key 由内核自动生成（需一次性展示）；false=用户自定义（无需回显）。 */
  userKeyAutogenerated?: boolean;
}

export interface PendingWoaLogin {
  token: string;
  instanceId: string;
  identity: ExternalIdentity;
  expiresAt: number;
}

/**
 * 用户自填 user_key 的格式约束。
 *
 * 本端点允许"key 不存在即建号"（首次登录即注册），是**无凭据**的公开入口，
 * 因此即便不设开关，也必须挡住三类输入，否则等于开放一个可任意写库的口子：
 * - 过短（含空串）：任何人随手敲几个字符就能批量建号；
 * - 过长：超长串会打爆存储 / 日志；
 * - 含控制字符 / 空白：换行会污染日志（CRLF 注入），空格会造成"看起来一样的两把 key"。
 *
 * 只做长度与字符集约束，不校验 `sk-mem-` 前缀——用户自己的 key 可能来自任意体系
 * （如 CodeBuddy 下发的 key），强制前缀会直接否定"兼容用户自持 key"这个目标。
 */
const USER_KEY_MIN_LENGTH = 8;
const USER_KEY_MAX_LENGTH = 256;
// 用 Unicode 属性类 \p{Cc} 表达"控制字符"，而不是在正则里写 \x00-\x1f 这类
// 控制字符转义（会触发 no-control-regex）；覆盖面也更全（含 U+0080–U+009F）。
const USER_KEY_PATTERN = /^[^\s\p{Cc}]+$/u;

function assertUsableUserKey(key: string): string {
  const trimmed = key.trim();
  if (!trimmed) {
    throw new PanelAuthError('INVALID_USER_KEY', 'user_key must not be empty', 400);
  }
  if (trimmed.length < USER_KEY_MIN_LENGTH) {
    throw new PanelAuthError(
      'INVALID_USER_KEY',
      `user_key must be at least ${USER_KEY_MIN_LENGTH} characters`,
      400,
    );
  }
  if (trimmed.length > USER_KEY_MAX_LENGTH) {
    throw new PanelAuthError(
      'INVALID_USER_KEY',
      `user_key must be at most ${USER_KEY_MAX_LENGTH} characters`,
      400,
    );
  }
  if (!USER_KEY_PATTERN.test(trimmed)) {
    throw new PanelAuthError(
      'INVALID_USER_KEY',
      'user_key must not contain whitespace or control characters',
      400,
    );
  }
  return trimmed;
}

interface PendingWoaPayload {
  version: 1;
  instanceId: string;
  identity: Omit<ExternalIdentity, 'claims'>;
  expiresAt: number;
  nonce: string;
}

interface PanelAuthDependencies {
  config: PanelAuthConfig;
  instances: InstanceRegistry;
  metaKernel: MetaKernelPort;
  logger: Logger;
}

export class PanelAuthService {
  private readonly config: PanelAuthConfig;
  private readonly instances: InstanceRegistry;
  private readonly metaKernel: MetaKernelPort;
  private readonly logger: Logger;
  private readonly sessions: MemorySessionStore;
  private readonly identities: FileIdentityStore;
  private readonly providers = new AuthProviderRegistry();
  private readonly consumedPendingWoa = new Set<string>();

  constructor(dependencies: PanelAuthDependencies) {
    const { config, instances, metaKernel, logger } = dependencies;
    this.config = config;
    this.instances = instances;
    this.metaKernel = metaKernel;
    this.logger = logger;
    if (!config.userKeyEnabled && !config.idpEnabled) {
      throw new Error('at least one Panel authentication method must be enabled');
    }
    // sessionSecret 由配置层内部生成并持久化到 0600 文件（不接受外部配置），
    // 为空说明生成/读取失败——这是内部故障，不是漏配，错误据此表述。
    if (config.idpEnabled && !config.sessionSecret) {
      throw new Error('session secret is unavailable: internal generation or persistence failed');
    }
    this.sessions = new MemorySessionStore(config.sessionTtlSeconds);
    this.identities = new FileIdentityStore(config.identityStorePath);
    // Provider 统一走 registry：删除历史上的私有 `this.woa` 字段。
    // 将来接第二个 Provider（OAuth2/OIDC）时，只需在这里新增 `providers.register(...)`，
    // 不需要在 Service 上再增加同名字段。
    if (config.idpEnabled && config.woa.enabled) {
      this.providers.register(new WoaProvider({
        enabled: config.woa.enabled,
        appToken: config.woa.appToken,
        safeMode: config.woa.safeMode,
        requireSignature: config.woa.requireSignature,
        appUrl: config.woa.appUrl,
        loginUrl: config.woa.loginUrl,
        logoutUrl: config.woa.logoutUrl,
        paasId: config.woa.paasId,
        authProvider: config.woa.authProvider,
      }));
    }
  }

  listMethods(): AuthMethodView[] {
    const methods: AuthMethodView[] = [];
    if (this.config.userKeyEnabled) {
      methods.push({ id: 'user_key', type: 'user_key', display_name: 'user_key', enabled: true });
    }
    // 类型字段暂保留字面量 'woa'（前端 LoginGate.tsx / auth.ts / i18n 已按此断言）；
    // 命名泛化列为 PR-3 的路由/契约扩展任务，与本 PR 无关。
    const woa = this.providers.get('woa');
    if (woa) {
      methods.push({ id: 'woa', type: 'woa', display_name: woa.displayName, enabled: true });
    }
    return methods;
  }

  /**
   * 供 ingress / callback 路由枚举活的 header-injected Provider（如 WOA）。
   *
   * 仅返回**已注册**的 Provider，未启用即空数组——路由据此决定是否处理带
   * `ingressHeaderName` 的请求，避免"未开 WOA 却仍被 WOA 流程绑架"。
   */
  listHeaderInjectedProviders(): HeaderInjectedProvider[] {
    return this.providers.listByKind('header-injected');
  }

  buildWoaLoginUrl(instanceId: string, returnTo: string): string {
    const provider = this.requireWoa();
    this.requireInstance(instanceId);
    const callback = this.buildCallbackUrl(instanceId, returnTo);
    return provider.buildLoginUrl(callback);
  }

  buildWoaLogoutUrl(returnTo: string): string {
    return this.requireWoa().buildLogoutUrl(this.safeReturnTo(returnTo));
  }

  async completeWoaLogin(
    ...[instanceId, headers, _returnTo, requestId]: [
      string,
      Record<string, string | undefined>,
      string,
      (string | undefined)?,
    ]
  ): Promise<IdpLoginResult> {
    const provider = this.requireWoa();
    const identity = await provider.authenticateFromHeaders(headers);
    if (!identity) throw new PanelAuthError('WOA_IDENTITY_INVALID', 'WOA identity headers are invalid', 401);
    const resolved = await this.resolveIdentity(instanceId, identity, requestId);
    const session = this.sessions.create({
      instanceId,
      coreUserId: resolved.coreUserId,
      userKey: resolved.userKey,
      providerId: identity.providerId,
      externalSubject: identity.subject,
      displayName: identity.displayName ?? identity.loginName,
      user: resolved.user,
    });
    return { session, identity };
  }

  async createPendingWoaLogin(input: {
    instanceId: string;
    headers: Record<string, string | undefined>;
  }): Promise<PendingWoaLogin> {
    const identity = await this.requireWoa().authenticateFromHeaders(input.headers);
    if (!identity) throw new PanelAuthError('WOA_IDENTITY_INVALID', 'WOA identity headers are invalid', 401);
    this.requireInstance(input.instanceId);
    const expiresAt = Date.now() + 5 * 60 * 1000;
    const payload: PendingWoaPayload = {
      version: 1,
      instanceId: input.instanceId,
      identity: {
        providerId: identity.providerId,
        subject: identity.subject,
        loginName: identity.loginName,
        displayName: identity.displayName,
        email: identity.email,
        staffId: identity.staffId,
        departmentId: identity.departmentId,
        departmentName: identity.departmentName,
      },
      expiresAt,
      nonce: randomUUID(),
    };
    const token = encryptSecret(JSON.stringify(payload), this.config.sessionSecret);
    return { token, instanceId: input.instanceId, identity, expiresAt };
  }

  getPendingWoaLogin(token: string | undefined): PendingWoaLogin | null {
    // WOA 关闭时"完全无感"：即使浏览器残留旧 pending Cookie，也不响应。
    // 否则 /auth/session 会返回 pending=true，前端渲染 WOA 确认页 → 存在跳 WOA 按钮
    // → 用户点击后 loginWoa() 整页跳到 WOA_LOGIN_URL，破坏"未开 WOA 应像开发前一样"。
    if (!this.providers.get('woa')) return null;
    if (!token || this.consumedPendingWoa.has(token)) return null;
    try {
      const parsed = JSON.parse(decryptSecret(token, this.config.sessionSecret)) as unknown;
      if (!parsed || typeof parsed !== 'object') return null;
      const payload = parsed as Partial<PendingWoaPayload>;
      const identity = payload.identity;
      if (
        payload.version !== 1 ||
        typeof payload.instanceId !== 'string' ||
        typeof payload.expiresAt !== 'number' ||
        !identity ||
        typeof identity !== 'object' ||
        typeof identity.providerId !== 'string' ||
        typeof identity.subject !== 'string' ||
        typeof identity.loginName !== 'string'
      ) return null;
      if (payload.expiresAt <= Date.now()) return null;
      return {
        token,
        instanceId: payload.instanceId,
        identity: { ...identity, claims: {} } as ExternalIdentity,
        expiresAt: payload.expiresAt,
      };
    } catch {
      return null;
    }
  }

  /**
   * 取外部认证体系下的唯一用户 id（对应 core 的 meta_users.external_id）。
   *
   * 优先用工号（staffId）——它是稳定的、不会变的标识；
   * 仅在工号缺失时回落到 subject（provider 侧已保证 subject = staffId || loginName）。
   * 不用 loginName 作为首选：登录名可能因改名/规范化而变，会导致绑定关系失效。
   */
  private externalAuthIdOf(identity: {
    staffId?: string;
    subject: string;
    loginName: string;
  }): string {
    const staffId = identity.staffId?.trim();
    if (staffId) return staffId;
    return identity.subject.trim() || identity.loginName.trim();
  }

  /**
   * 预览：用户填的 user_key 在 core 里是否已存在。
   *
   * 首次外部认证登录的关键防误绑环节——让用户先看清"这把 key 属于谁"，
   * 再确认是绑定它还是新建账号，而不是默默替他做决定：
   * - key 已存在 → 返回该账号信息（user_id/username），用户确认后**绑定**它，老数据完整保留；
   * - key 不存在 → 用户确认后用这把 key **新建**账号。
   */
  async previewPendingWoaLogin(input: {
    token: string;
    userKey: string;
    requestId?: string;
  }): Promise<{
    exists: boolean;
    user_id?: string;
    username?: string;
    display_name?: string;
    user_type?: string;
  }> {
    const pending = this.getPendingWoaLogin(input.token);
    if (!pending) throw new PanelAuthError('WOA_LOGIN_EXPIRED', 'WOA login confirmation expired', 401);

    const entry = this.requireInstance(pending.instanceId);
    const context = this.context(entry, entry.api_key, input.requestId);
    const key = input.userKey.trim();
    if (!key) {
      throw new PanelAuthError('INVALID_USER_KEY', 'user_key must not be empty', 400);
    }

    const verified = await this.metaKernel.invoke('auth/verify', { user_key: key }, context);
    // 先判有效性再交给 readVerifiedUser：后者对无效 key 抛错，
    // 而"key 不存在"是这里的正常分支，不该靠 catch 掩盖（那会连网络/解析错误一起吞掉）。
    const data = verified?.data as { valid?: boolean } | null;
    if (verified?.code !== 0 || data?.valid !== true) return { exists: false };

    const { user } = this.readVerifiedUser(verified);
    return {
      exists: true,
      user_id: user.user_id,
      username: user.username,
      display_name: user.display_name,
      user_type: user.user_type,
    };
  }

  async completePendingWoaLogin(input: {
    token: string;
    username?: string;
    userKey?: string;
    customUserKey?: string;
    requestId?: string;
  }): Promise<IdpLoginResult> {
    const pending = this.getPendingWoaLogin(input.token);
    if (!pending) throw new PanelAuthError('WOA_LOGIN_EXPIRED', 'WOA login confirmation expired', 401);

    // 外部认证首次登录：用户必须提供一把 user_key——
    // - 系统内已存在 → 绑定到该存量账号（老数据完整保留）；
    // - 不存在 → 用这把 key 新建账号。
    // 用户应在提交前先调 previewPendingWoaLogin 看清这把 key 属于谁，再确认。
    const userKey = input.userKey?.trim() || input.customUserKey?.trim();
    if (!userKey) {
      throw new PanelAuthError('INVALID_USER_KEY', 'user_key is required', 400);
    }
    const resolved = await this.provisionIdentity({
      instanceId: pending.instanceId,
      identity: pending.identity,
      requestId: input.requestId,
      username: input.username?.trim() || undefined,
      customUserKey: userKey,
    });
    this.consumedPendingWoa.add(input.token);
    const session = this.sessions.create({
      instanceId: pending.instanceId,
      coreUserId: resolved.coreUserId,
      userKey: resolved.userKey,
      providerId: pending.identity.providerId,
      externalSubject: pending.identity.subject,
      displayName: pending.identity.displayName ?? pending.identity.loginName,
      user: resolved.user,
    });
    return {
      session,
      identity: pending.identity,
      // key 由用户提供（无论绑定存量还是新建），无需回显。
      userKeyDisplay: undefined,
      userKeyAutogenerated: false,
    };
  }

  /**
   * 预览：用户自填的 user_key 在系统内是否已有对应账号。
   *
   * 与 previewPendingWoaLogin 同构，服务于「兼容用户自持 key」的登录：
   * - key 已存在 → 返回账号信息（user_id/username），用户确认后**登录**它；
   * - key 不存在 → 用户确认后用这把 key **新建**账号并登录。
   *
   * 两步确认是为了防误绑：先让用户看清"这把 key 属于谁"，再决定登录还是新建，
   * 而不是在登录请求里默默替他建号。
   */
  async previewUserKeyLogin(input: {
    instanceId: string;
    userKey: string;
    requestId?: string;
  }): Promise<{
    exists: boolean;
    user_id?: string;
    username?: string;
    display_name?: string;
    user_type?: string;
  }> {
    const key = assertUsableUserKey(input.userKey);
    const entry = this.requireInstance(input.instanceId);
    // 预览是"只读探测"，用实例 admin key 作为网关 Bearer（无用户凭据可用）；
    // auth/verify 只按 body 里的 user_key 判定，不读取调用方身份。
    const context = this.context(entry, entry.api_key, input.requestId);
    const verified = await this.metaKernel.invoke('auth/verify', { user_key: key }, context);
    const data = verified?.data as { valid?: boolean } | null;
    if (verified?.code !== 0 || data?.valid !== true) return { exists: false };

    const { user } = this.readVerifiedUser(verified);
    return {
      exists: true,
      user_id: user.user_id,
      username: user.username,
      display_name: user.display_name,
      user_type: user.user_type,
    };
  }

  /**
   * 用用户自填的 user_key 登录；key 不存在时新建账号（首次登录即注册）。
   *
   * 调用方需先经 previewUserKeyLogin 让用户确认归属（两步确认），
   * 本方法只负责执行。
   */
  async loginWithUserKey(input: {
    instanceId: string;
    userKey: string;
    username?: string;
    requestId?: string;
  }): Promise<{ user_id: string; user: SessionUser; created: boolean }> {
    const key = assertUsableUserKey(input.userKey);
    const entry = this.requireInstance(input.instanceId);
    const context = this.context(entry, entry.api_key, input.requestId);

    // 已存在 → 直接登录，不建号。
    const probe = await this.metaKernel.invoke('auth/verify', { user_key: key }, context);
    const probeData = probe?.data as { valid?: boolean } | null;
    if (probe?.code === 0 && probeData?.valid === true) {
      const { user_id, user } = this.readVerifiedUser(probe);
      return { user_id, user, created: false };
    }

    // 不存在 → 用这把 key 建号。
    // user/create-with-key 是 admin 级接口（core 侧 assertCanManageUsers），
    // 用实例 api_key 作为 user_key 调用（见 §12.3：单一 admin 凭证来源）。
    const username = input.username?.trim() || this.usernameFromKey(key);
    const created = await this.metaKernel.invoke(
      'user/create-with-key',
      { username, user_key: key },
      context,
    );
    if (!created || created.code !== 0) {
      // 409 duplicate_user_key：并发下别人抢先建了同 key 账号，退化为登录。
      if (created?.code === 409) {
        const { user_id, user } = await this.verifyCoreUser(input.instanceId, key, input.requestId);
        return { user_id, user, created: false };
      }
      throw new PanelAuthError(
        'USER_CREATE_FAILED',
        created?.message || 'failed to create user with the provided key',
        502,
      );
    }
    const { user_id, user } = await this.verifyCoreUser(input.instanceId, key, input.requestId);
    return { user_id, user, created: true };
  }

  /** 建号时的默认 username：截取 key 的可读片段，避免一长串密钥直接当展示名。 */
  private usernameFromKey(key: string): string {
    const tail = key.length > 12 ? key.slice(-12) : key;
    return `user-${tail}`;
  }

  /**
   * 放弃当前 WOA 待确认登录（用户选择改用 user_key 登录）。
   *
   * 只是把 pending token 标记为已消费（不可再完成建号），真正的"别再把我弹回 WOA 确认页"
   * 由路由层下发的 dismissed Cookie 保证（网关每次请求都会注入身份头，仅靠内存标记会在
   * 进程重启后失效，且刷新页面会立刻重建 pending）。
   */
  dismissPendingWoaLogin(token: string | undefined): void {
    if (token) this.consumedPendingWoa.add(token);
  }

  async bindWoaIdentity(
    ...[instanceId, userKey, headers, requestId]: [
      string,
      string,
      Record<string, string | undefined>,
      (string | undefined)?,
    ]
  ): Promise<{ coreUserId: string; identity: ExternalIdentity }> {
    const provider = this.requireWoa();
    const identity = await provider.authenticateFromHeaders(headers);
    if (!identity) throw new PanelAuthError('WOA_IDENTITY_INVALID', 'WOA identity headers are invalid', 401);
    const entry = this.requireInstance(instanceId);
    const context = this.context(entry, userKey, requestId);
    const verified = await this.metaKernel.invoke('auth/verify', { user_key: userKey }, context);
    const user = this.readVerifiedUser(verified);
    this.saveIdentityBinding(instanceId, identity, user.user_id, userKey);
    return { coreUserId: user.user_id, identity };
  }

  resolveSession(instanceId: string, cookieToken: string | undefined): IdpSession | null {
    const session = this.sessions.get(cookieToken);
    return session?.instanceId === instanceId ? session : null;
  }

  getSession(cookieToken: string | undefined): IdpSession | null {
    return this.sessions.get(cookieToken);
  }

  destroySession(cookieToken: string | undefined): void {
    this.sessions.destroy(cookieToken);
  }

  async resolveIdentity(
    instanceId: string,
    identity: ExternalIdentity,
    requestId?: string,
  ): Promise<{ coreUserId: string; userKey: string; user: SessionUser }> {
    const existing = this.identities.find(instanceId, identity.providerId, identity.subject);
    if (existing) {
      let userKey: string;
      try {
        userKey = decryptSecret(existing.encryptedUserKey, this.config.sessionSecret);
      } catch {
        throw new PanelAuthError('IDENTITY_BINDING_CORRUPT', 'stored IdP identity binding cannot be decrypted', 500);
      }
      const verified = await this.verifyCoreUser(instanceId, userKey, requestId);
      return {
        coreUserId: existing.coreUserId,
        userKey,
        user: verified.user,
      };
    }

    // 本地绑定文件缺失（卷丢失 / session-secret 轮换 / 跨部署）时的兜底：
    // 直接按外部身份 (auth_provider, external_id) 反查 Core，命中即视为存量登录，
    // 不再强制用户重新填 key 走首次绑定。该路径由 WOA=on 自身驱动（Panel 已启用
    // WOA 才会走到这里），不引入任何 default-off 开关。
    const resolvedFromCore = await this.resolveIdentityFromCore(instanceId, identity, requestId);
    if (resolvedFromCore) return resolvedFromCore;

    throw new PanelAuthError(
      'IDENTITY_NOT_BOUND',
      'WOA identity is authenticated but has not been bound to a Memory user',
      403,
    );
  }

  /**
   * 本地绑定缺失时，用外部身份反查 Core 完成登录（无需本地绑定文件）。
   *
   * 流程：
   *   ① user/find-by-external 按 (auth_provider, external_id) 反查 → 拿 core user_id；
   *      未命中 → 返回 null（交由上层按"真·首次登录"处理）。
   *   ② user-key/create 用实例 api_key 为该账号签发一把新 user_key
   *      （Core 不返回既有 key 明文，故只能新签；后续 meta 请求用它作 x-tdai-user-key）。
   *   ③ 回写本地绑定缓存，加速下次登录并降低 Core 往返。
   *
   * 全程只用实例 api_key（system_admin），符合"单一 admin 凭证来源"。
   */
  private async resolveIdentityFromCore(
    instanceId: string,
    identity: ExternalIdentity,
    requestId?: string,
  ): Promise<{ coreUserId: string; userKey: string; user: SessionUser } | null> {
    const externalId = this.externalAuthIdOf(identity);
    if (!externalId) return null;
    const entry = this.requireInstance(instanceId);
    const context = this.context(entry, entry.api_key, requestId);

    // 按 external_id 反查两类账号，二者的 auth_provider 不同：
    //   ① WOA 首次登录新建的号 → provisionIdentity 建号时 auth_provider=woa；
    //   ② 存量账号绑定 WOA 的号 → Core bindExternalIdentity 故意"只写 external_id、
    //      不改 auth_provider"，仍保持建号时的 provider（通常是 local）。
    // 因此单一 provider 会漏掉另一类，需按 woa → 默认(local) 依次反查。
    // 不会误命中：未绑定外部身份的账号 external_id 兜底为 usr-xxx 格式，与工号数字不同。
    const coreUserId = await this.lookupCoreUserByExternal(externalId, context);
    if (!coreUserId) return null;

    // 为反查到的账号签发一把新 user_key（Core 不下发既有 key 明文）。
    const issued = await this.metaKernel.invoke(
      'user-key/create',
      { user_id: coreUserId, name: 'woa-login' },
      context,
    );
    if (issued?.code !== 0 || !issued.data || typeof issued.data !== 'object') {
      // 达到活跃 key 上限等情况：不硬失败卡死，返回 null 让上层走首次登录 pending，
      // 由用户在确认页用自己的一把 user_key 完成绑定（该 key 会被复用，不再新签）。
      this.logger.warn('WOA core-fallback key issue failed, degrading to pending', {
        instanceId, coreUserId, code: issued?.code, message: issued?.message,
      });
      return null;
    }
    const userKey = (issued.data as { key_value?: unknown }).key_value;
    if (typeof userKey !== 'string' || !userKey) {
      throw new PanelAuthError('WOA_KEY_ISSUE_INVALID', 'Core returned an invalid user_key', 502);
    }

    const verified = await this.verifyCoreUser(instanceId, userKey, requestId);
    // 回写本地绑定缓存：下次登录直接命中本地路径，无需再打 Core。
    // 回写失败（卷只读 / 磁盘满）不阻断本次登录——下次仍可经 Core 反查兜底。
    try {
      this.saveIdentityBinding(instanceId, identity, coreUserId, userKey);
    } catch (err) {
      this.logger.warn('WOA identity binding cache write failed (non-fatal)', {
        instanceId, coreUserId, err: err instanceof Error ? err.message : String(err),
      });
    }
    return { coreUserId, userKey, user: verified.user };
  }

  /**
   * 按 external_id 反查 Core 账号，覆盖两类不同 auth_provider 的账号。
   *
   * 依次尝试：
   *   ① auth_provider=woa —— WOA 首次登录新建的号；
   *   ② 省略 auth_provider（Core 兜底为 local）—— 存量账号绑定 WOA 的号。
   * 命中即返回 user_id；都未命中返回 null（交由上层按首次登录处理）。
   */
  private async lookupCoreUserByExternal(
    externalId: string,
    context: ReturnType<PanelAuthService['context']>,
  ): Promise<string | null> {
    // 当前只挂 WOA 一个 Provider，直接用 requireWoa().authProviderDomain 与
    // config.woa.authProvider 等价；接第二个 Provider 时，该 domain 应改为
    // "本次处理的 identity 所属 Provider 的 domain"（沿调用链传入 identity.providerId）。
    const providers: Array<string | undefined> = [this.requireWoa().authProviderDomain, undefined];
    const tried = new Set<string>();
    for (const provider of providers) {
      const dedupKey = provider ?? '__default__';
      if (tried.has(dedupKey)) continue;
      tried.add(dedupKey);
      const body: Record<string, string> = { external_id: externalId };
      if (provider) body.auth_provider = provider;
      const found = await this.metaKernel.invoke('user/find-by-external', body, context);
      if (found?.code !== 0) {
        this.logger.warn('WOA core-fallback find-by-external errored', {
          provider: dedupKey, code: found?.code, message: found?.message,
        });
        continue;
      }
      const data = found.data;
      if (!data || typeof data !== 'object') continue;
      const coreUserId = (data as { user_id?: unknown }).user_id;
      if (typeof coreUserId === 'string' && coreUserId) return coreUserId;
    }
    return null;
  }

  /**
   * 建立外部认证关联：把外部唯一 id（工号）绑到 core 的 user（写独立关联表）。
   *
   * 存量绑定与新建账号都走这里，保证两条路径的关联语义一致。
   * 关联失败必须让整个流程失败——否则下次登录会被误判为"初次"，要求重新填 key。
   */
  private async bindExternalAuth(
    coreUserId: string,
    identity: ExternalIdentity,
    context: ReturnType<PanelAuthService['context']>,
  ): Promise<void> {
    const externalAuthId = this.externalAuthIdOf(identity);
    if (!externalAuthId) {
      throw new PanelAuthError(
        'EXTERNAL_AUTH_ID_MISSING',
        'external identity does not carry a usable user id (staffId/subject)',
        400,
      );
    }
    // auth_provider / display_name 一并落库，与建号路径保持同一个外部域，
    // 避免"绑定写 A 域、鉴权按 B 域查"导致的 401；展示名让成员列表显示中文名
    // 而非登录名（core 侧仅在目标账号 display_name 为空时补写，不覆盖）。
    await this.metaKernel.invoke('user/bind-external', {
      user_id: coreUserId,
      external_id: externalAuthId,
      auth_provider: this.requireWoa().authProviderDomain,
      display_name: identity.displayName?.trim() || undefined,
    }, context);
  }

  private async provisionIdentity(input: {
    instanceId: string;
    identity: ExternalIdentity;
    requestId?: string;
    username?: string;
    customUserKey?: string;
  }): Promise<{ coreUserId: string; userKey: string; user: SessionUser }> {
    const { instanceId, identity, requestId, customUserKey } = input;
    const entry = this.requireInstance(instanceId);
    // 幂等兜底：并发/重复提交时可能在前一次建号写盘前再次进入，
    // 此前靠"user_id = 登录名"的唯一约束挡住重复建号；改为内核生成 usr-xxx 后
    // 该约束消失，必须在建号前显式检查绑定是否已经存在。
    const alreadyBound = this.identities.find(instanceId, identity.providerId, identity.subject);
    if (alreadyBound) return this.resolveIdentity(instanceId, identity, requestId);
    // WOA 建号：username 默认取 WOA 登录名（可在确认页修改），与 user_id 解耦。
    // user_id **不**使用登录名，交给内核按 admin「新建并绑定账号」同一套逻辑生成 usr-xxx，
    // 避免把外部身份标识写进主键（改名/重名/跨 IdP 冲突会直接破坏归属关系）。
    const username = (input.username || identity.loginName || identity.subject).trim();
    if (!/^[A-Za-z0-9_-]+$/.test(username)) {
      throw new PanelAuthError('INVALID_USERNAME', 'username must contain only letters, numbers, underscores, or hyphens', 400);
    }
    if (customUserKey !== undefined && customUserKey.length < 8) {
      throw new PanelAuthError('INVALID_CUSTOM_USER_KEY', 'custom user_key is too short', 400);
    }
    // 建号要求 system_admin：user/create(-with-key) 的 assertCanManageUsers 不再有
    // "无 user-key 白名单"分支，必须带 admin user_key。
    // 单一凭证来源（见 §12.3）：统一用实例 api_key，不再另设 admin key 配置项。
    // 部署前提：实例 api_key 必须能在 core 侧解析为 system_admin，否则建号 401。
    const context = this.context(entry, entry.api_key, requestId);

    // 存量账号接入：用户给的 key 若在系统内已存在，把外部身份绑定到**那个已有账号**，
    // 而不是新建——这样老数据（memories/teams/skills）原样保留。
    if (customUserKey) {
      // verifyCoreUser 在 key 无效/不存在时会抛错，这里需要"查不到就返回 null"的语义，
      // 故单独调 auth/verify 并自行判定，不走 verifyCoreUser。
      const envelope = await this.metaKernel.invoke(
        'auth/verify',
        { user_key: customUserKey },
        this.context(entry, customUserKey, requestId),
      );
      const data = envelope?.data as { valid?: boolean } | null;
      const existingId = envelope?.code === 0 && data?.valid === true
        ? this.readVerifiedUser(envelope).user_id
        : undefined;
      if (existingId) {
        // 幂等：并发/重试时可能已绑定，bindExternalIdToUser 内部已处理。
        await this.bindExternalAuth(existingId, identity, context);
        const verified = await this.verifyCoreUser(instanceId, customUserKey, requestId);
        return { coreUserId: verified.user_id, userKey: customUserKey, user: verified.user };
      }
    }

    // 与 admin「新建并绑定账号」一致：不传 user_id，由内核生成 usr-xxx；
    // 默认 user/create 由内核生成 key；显式自定义 key 走 user/create-with-key。
    //
    // 建号即带上外部身份三元组（external_id / auth_provider / display_name）：
    // 与 bindExternalAuth 走同一个外部域，保证建号后立刻能被 find-by-external
    // 反查到。建号后再调 bind-external 也能补上，但多一次往返且中途失败会留下
    // "已建号、未绑定"的孤儿账号。
    const identityFields = {
      external_id: this.externalAuthIdOf(identity) || undefined,
      auth_provider: this.requireWoa().authProviderDomain,
      display_name: identity.displayName?.trim() || undefined,
      ...(identity.email?.trim() ? { email: identity.email.trim() } : {}),
    };
    const created = customUserKey
      ? await this.metaKernel.invoke('user/create-with-key', { username, user_key: customUserKey, ...identityFields }, context)
      : await this.metaKernel.invoke('user/create', { username, ...identityFields }, context);
    if (created.code !== 0 || !created.data || typeof created.data !== 'object') {
      // 自定义 key 与系统内已有 key 重复时，Core 返回 duplicate_user_key（409），透传给前端。
      const raw = created.message || '';
      if (raw.includes('duplicate_user_key')) {
        throw new PanelAuthError('WOA_CUSTOM_KEY_DUPLICATE', 'custom user_key already exists', 409);
      }
      // user_id 已存在（同名 WOA 用户重复建号）。
      if (raw.includes('duplicate') || raw.includes('already exists')) {
        throw new PanelAuthError('WOA_USER_ALREADY_EXISTS', 'a user with this id already exists', 409);
      }
      throw new PanelAuthError('WOA_PROVISION_FAILED', raw || 'failed to provision WOA user', 502);
    }
    const result = created.data as { user_id?: unknown; default_user_key?: unknown };
    if (typeof result.user_id !== 'string' || typeof result.default_user_key !== 'string') {
      throw new PanelAuthError('WOA_PROVISION_INVALID', 'Core returned an invalid provision response', 502);
    }
    // 新建的账号也要写外部认证关联，否则下次登录查不到、会被当成初次再让填一次 key。
    // 放在加团队之前：关联比加团队更基础，先确保身份链路完整。
    await this.bindExternalAuth(result.user_id, identity, context);
    if (this.config.woa.defaultTeamId) {
      // team-member/add 需 system_admin。凭证与建号保持一致（实例 api_key），
      // 全程只用这一个来源，避免两套 admin 凭证。
      const added = await this.metaKernel.invoke('team-member/add', {
        team_id: this.config.woa.defaultTeamId,
        user_id: result.user_id,
        role: this.config.woa.defaultRole,
      }, context);
      if (added.code !== 0) {
        throw new PanelAuthError('WOA_TEAM_PROVISION_FAILED', added.message || 'failed to add WOA user to team', 502);
      }
    }
    this.identities.save({
      instanceId,
      providerId: identity.providerId,
      externalSubject: identity.subject,
      coreUserId: result.user_id,
      encryptedUserKey: encryptSecret(result.default_user_key, this.config.sessionSecret),
      displayName: identity.displayName ?? identity.loginName,
      updatedAt: new Date().toISOString(),
    });
    this.logger.info('WOA identity provisioned', {
      instanceId,
      providerId: identity.providerId,
      externalSubject: identity.subject,
      coreUserId: result.user_id,
    });
    const verified = await this.verifyCoreUser(instanceId, result.default_user_key, requestId);
    return { coreUserId: result.user_id, userKey: result.default_user_key, user: verified.user };
  }

  private saveIdentityBinding(
    ...[instanceId, identity, coreUserId, userKey]: [string, ExternalIdentity, string, string]
  ): void {
    this.identities.save({
      instanceId,
      providerId: identity.providerId,
      externalSubject: identity.subject,
      coreUserId,
      encryptedUserKey: encryptSecret(userKey, this.config.sessionSecret),
      displayName: identity.displayName ?? identity.loginName,
      updatedAt: new Date().toISOString(),
    });
  }

  private requireWoa(): HeaderInjectedProvider {
    const provider = this.providers.get('woa');
    if (!provider || provider.kind !== 'header-injected') {
      throw new PanelAuthError('AUTH_METHOD_DISABLED', 'WOA authentication is disabled', 404);
    }
    return provider as HeaderInjectedProvider;
  }

  private requireInstance(instanceId: string) {
    try {
      return this.instances.resolve(instanceId);
    } catch {
      throw new PanelAuthError('INVALID_INSTANCE', 'invalid metadata instance', 400);
    }
  }

  private context(entry: ReturnType<InstanceRegistry['resolve']>, userKey: string, requestId?: string): MetaCallContext {
    return {
      instanceId: entry.instance_id,
      gatewayEndpoint: entry.gateway_endpoint,
      gatewayApiKey: entry.api_key,
      userKey,
      reqId: requestId,
    };
  }

  private async verifyCoreUser(
    instanceId: string,
    userKey: string,
    requestId?: string,
  ): Promise<{ user_id: string; user: SessionUser }> {
    const entry = this.requireInstance(instanceId);
    const envelope = await this.metaKernel.invoke(
      'auth/verify',
      { user_key: userKey },
      this.context(entry, userKey, requestId),
    );
    return this.readVerifiedUser(envelope);
  }

  private readVerifiedUser(
    envelope: { code: number; message: string; data: unknown },
  ): { user_id: string; user: SessionUser } {
    const data = envelope.data as { valid?: boolean; user?: SessionUser } | null;
    if (
      envelope.code !== 0 ||
      data?.valid !== true ||
      !data.user ||
      typeof data.user.user_id !== 'string'
    ) {
      throw new PanelAuthError('INVALID_USER_KEY', 'user_key verification failed', 401);
    }
    return { user_id: data.user.user_id, user: data.user };
  }

  private buildCallbackUrl(instanceId: string, _returnTo: string): string {
    this.requireInstance(instanceId);
    // WOA 回跳 APP_URL 根路径，身份由网关通过请求头注入。
    return `${this.config.woa.appUrl.replace(/\/+$/, '')}/`;
  }

  private safeReturnTo(value: string): string {
    if (!value || !value.startsWith('/') || value.startsWith('//')) return '/';
    return value;
  }
}
